version: '3'
services:
  openssh:
    build:
      context: .
      dockerfile: Dockerfile.openssh
    image: ymbihq/openssh
    privileged: true
    network_mode: host
    env_file:
        - .env
    volumes:
      - ./data:/data
    restart: unless-stopped
  closessh:
    build:
      context: .
      dockerfile: Dockerfile.closessh
    image: ymbihq/closessh
    privileged: true
    network_mode: host
    env_file:
        - .env
    volumes:
      - ./data:/data
    restart: unless-stopped
